image: java:8

stages:
 - build
 - deploy

before_install:
 - chmod +x gradlew

build:
 stage: build
 script: ./mvnw package
 artifacts:
  paths:
    - target/receita-0.0.1-SNAPSHOT.jar
 
production:
 stage: deploy
 image: ruby:2.3
 script:
 - apt-get update -qy
 - apt-get install -y ruby-dev
 - gem install dpl
 - dpl --provider=heroku --app=receita-api-spring-boot --api-key=$HEROKU_API_KEY