image: maven:3-jdk-8 

before_script:
    - java -version
    - mvn -version

    variables:
      MAVEN_OPTS: "-Dmaven.repo.local=.m2"

cache:
  paths:
    - .m2/

stages:
  - deploy

deploy:
  type: deploy
  script:
  - dpl --provider=heroku --app=receita-api-spring-boot --api-key=$HEROKU_API_KEY